"""Stage 1 — Cropped enemy classifier.

Trains a small CNN to classify 64x64 enemy crops into one of 17 classes.
- Input data: ./crops/<class>/<MAPxx>_<frame>_<idx>.png (generated by make_crops.py)
- Per-map train/val split is by filename prefix.
- 20 epochs, Adam lr=1e-3, CrossEntropyLoss.
- Saves best-by-val-accuracy weights to stage1_best.pt.
- Final report: val accuracy + per-class accuracy + most-confused pairs.
"""
import time
from pathlib import Path
import cv2
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

CROPS_DIR = Path("crops")
WEIGHTS_OUT = Path("stage1_best.pt")

# Order must match ENEMY_CLASSES in test.py / classes.txt (line indices = class IDs).
with open(Path("data") / "classes.txt") as f:
    ENEMY_CLASSES = [line.strip() for line in f
                     if line.strip() and not line.startswith("#")]
NUM_CLASSES = len(ENEMY_CLASSES)

# Map-name → split. Anything else is ignored (e.g., test maps).
TRAIN_MAPS = set(f"MAP{i:02d}" for i in range(1, 16)) | {"MAP31"}
VAL_MAPS   = set(f"MAP{i:02d}" for i in range(16, 26))

# ---- Dataset ---------------------------------------------------------------

class CropDataset(Dataset):
    """Loads pre-generated 64x64 enemy crops, filtered by allowed map names.
    Each filename starts with <MAPxx>_ which determines the split membership.
    """
    def __init__(self, root: Path, allowed_maps: set):
        self.items = []  # list of (path, class_id) pairs
        for class_id, name in enumerate(ENEMY_CLASSES):
            class_dir = root / name
            if not class_dir.is_dir():
                continue
            for f in class_dir.iterdir():
                if f.suffix != ".png":
                    continue
                map_name = f.name.split("_", 1)[0]
                if map_name in allowed_maps:
                    self.items.append((f, class_id))

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        path, class_id = self.items[idx]
        img = cv2.imread(str(path))                  # BGR uint8 (H, W, 3)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)   # RGB
        img = img.astype(np.float32) / 255.0         # to [0, 1]
        img = img.transpose(2, 0, 1)                 # (C, H, W) for torch
        return torch.from_numpy(img), class_id


# ---- Model -----------------------------------------------------------------

class SimpleCNN(nn.Module):
    """Three conv blocks + linear head. ~232k parameters. Designed for 64x64 input."""
    def __init__(self, num_classes=NUM_CLASSES):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1),  nn.ReLU(), nn.MaxPool2d(2),  # → 32×32×32
            nn.Conv2d(32, 64, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),  # → 64×16×16
            nn.Conv2d(64, 128, 3, padding=1),nn.ReLU(), nn.MaxPool2d(2),  # → 128×8×8
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128 * 8 * 8, num_classes),
        )

    def forward(self, x):
        return self.classifier(self.features(x))


# ---- Train / eval loops ----------------------------------------------------

def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()
    total_loss = 0.0
    correct = 0
    seen = 0
    for images, labels in loader:
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)
        logits = model(images)
        loss = criterion(logits, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * labels.size(0)
        correct += (logits.argmax(dim=1) == labels).sum().item()
        seen += labels.size(0)
    return total_loss / seen, correct / seen


@torch.no_grad()
def evaluate(model, loader, device, num_classes):
    model.eval()
    correct = 0
    seen = 0
    per_class_correct = torch.zeros(num_classes, dtype=torch.long)
    per_class_total   = torch.zeros(num_classes, dtype=torch.long)
    confusion = torch.zeros(num_classes, num_classes, dtype=torch.long)
    for images, labels in loader:
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)
        preds = model(images).argmax(dim=1)
        correct += (preds == labels).sum().item()
        seen += labels.size(0)
        for t, p in zip(labels.cpu(), preds.cpu()):
            confusion[t.item(), p.item()] += 1
            per_class_total[t.item()] += 1
            if t.item() == p.item():
                per_class_correct[t.item()] += 1
    return correct / seen, per_class_correct, per_class_total, confusion


def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")
    if device.type == "cuda":
        print(f"  GPU: {torch.cuda.get_device_name(0)}")

    train_ds = CropDataset(CROPS_DIR, TRAIN_MAPS)
    val_ds   = CropDataset(CROPS_DIR, VAL_MAPS)
    print(f"Train crops: {len(train_ds):,}")
    print(f"Val   crops: {len(val_ds):,}")

    train_loader = DataLoader(train_ds, batch_size=128, shuffle=True,
                              num_workers=2, pin_memory=(device.type == "cuda"))
    val_loader   = DataLoader(val_ds,   batch_size=256, shuffle=False,
                              num_workers=2, pin_memory=(device.type == "cuda"))

    model = SimpleCNN(num_classes=NUM_CLASSES).to(device)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"Model parameters: {n_params:,}")

    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

    EPOCHS = 20
    best_val = 0.0
    best_epoch = 0
    print("\nEpoch  train_loss  train_acc   val_acc   note")
    print("-" * 50)
    t0 = time.time()
    for epoch in range(1, EPOCHS + 1):
        tr_loss, tr_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
        val_acc, _, _, _ = evaluate(model, val_loader, device, NUM_CLASSES)
        marker = ""
        if val_acc > best_val:
            best_val = val_acc
            best_epoch = epoch
            torch.save(model.state_dict(), WEIGHTS_OUT)
            marker = "← best, saved"
        print(f" {epoch:2d}/{EPOCHS}    {tr_loss:.3f}     {tr_acc*100:5.1f}%    {val_acc*100:5.1f}%   {marker}")
    elapsed = time.time() - t0
    print("-" * 50)
    print(f"Trained in {elapsed/60:.1f} min")
    print(f"Best val accuracy: {best_val*100:.2f}% at epoch {best_epoch}")

    # Reload best weights and produce the final report
    model.load_state_dict(torch.load(WEIGHTS_OUT, map_location=device))
    val_acc, pcc, pct, conf = evaluate(model, val_loader, device, NUM_CLASSES)
    print(f"\n=== Final per-class val accuracy ===")
    for i, name in enumerate(ENEMY_CLASSES):
        t = int(pct[i])
        if t == 0:
            print(f"  {name:18s}    --     (no val instances)")
        else:
            acc = int(pcc[i]) / t * 100
            print(f"  {name:18s}  {acc:5.1f}%   ({int(pcc[i])}/{t})")

    # Most-confused class pairs (off-diagonal entries in the confusion matrix)
    print("\n=== Most-confused class pairs (true → predicted, count) ===")
    pairs = []
    for i in range(NUM_CLASSES):
        for j in range(NUM_CLASSES):
            if i == j:
                continue
            c = int(conf[i, j])
            if c > 0:
                pairs.append((c, ENEMY_CLASSES[i], ENEMY_CLASSES[j]))
    pairs.sort(reverse=True)
    for c, t_name, p_name in pairs[:10]:
        print(f"  {t_name:18s} -> {p_name:18s}  {c}")

    print(f"\nBest checkpoint saved to: {WEIGHTS_OUT.resolve()}")


if __name__ == "__main__":
    main()
